// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using universitydatalayer.dbcontext;

#nullable disable

namespace universitydatalayer.Migrations
{
    [DbContext(typeof(appdbcontext))]
    [Migration("20260126192144_addusers")]
    partial class addusers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("universitydatalayer.entities.course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("hours")
                        .HasColumnType("int");

                    b.Property<int?>("instructorid")
                        .HasColumnType("int");

                    b.Property<int>("maxstudents")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.HasIndex("instructorid");

                    b.ToTable("courses", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            hours = 30,
                            instructorid = 1,
                            maxstudents = 50,
                            name = "english"
                        },
                        new
                        {
                            id = 2,
                            hours = 60,
                            instructorid = 2,
                            maxstudents = 50,
                            name = "math"
                        });
                });

            modelBuilder.Entity("universitydatalayer.entities.instructor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("instructors", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "ahmed@gamil.com",
                            name = "ahmed hossam"
                        },
                        new
                        {
                            id = 2,
                            email = "youssef@gmail.com",
                            name = "youssef saad"
                        });
                });

            modelBuilder.Entity("universitydatalayer.entities.student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("students", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 29,
                            createdat = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "andrew@gmail.com",
                            isactive = true,
                            name = "andrew emad"
                        },
                        new
                        {
                            id = 2,
                            age = 27,
                            createdat = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "dina@gmail.com",
                            isactive = true,
                            name = "dina gamil"
                        });
                });

            modelBuilder.Entity("universitydatalayer.entities.studentcourse", b =>
                {
                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.Property<int>("courseid")
                        .HasColumnType("int");

                    b.Property<DateTime>("enrolldate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("grade")
                        .HasColumnType("int");

                    b.HasKey("studentid", "courseid");

                    b.HasIndex("courseid");

                    b.ToTable("studentcourses", (string)null);

                    b.HasData(
                        new
                        {
                            studentid = 1,
                            courseid = 1,
                            enrolldate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            studentid = 1,
                            courseid = 2,
                            enrolldate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            studentid = 2,
                            courseid = 1,
                            enrolldate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            studentid = 2,
                            courseid = 2,
                            enrolldate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("universitydatalayer.entities.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "admin@gmail.com",
                            password = "1234",
                            role = "admin"
                        },
                        new
                        {
                            id = 2,
                            email = "user@gmail.com",
                            password = "1234",
                            role = "user"
                        });
                });

            modelBuilder.Entity("universitydatalayer.entities.course", b =>
                {
                    b.HasOne("universitydatalayer.entities.instructor", "instructor")
                        .WithMany("courses")
                        .HasForeignKey("instructorid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("instructor");
                });

            modelBuilder.Entity("universitydatalayer.entities.studentcourse", b =>
                {
                    b.HasOne("universitydatalayer.entities.course", "course")
                        .WithMany("studentcourses")
                        .HasForeignKey("courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("universitydatalayer.entities.student", "student")
                        .WithMany("studentcourses")
                        .HasForeignKey("studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("universitydatalayer.entities.course", b =>
                {
                    b.Navigation("studentcourses");
                });

            modelBuilder.Entity("universitydatalayer.entities.instructor", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("universitydatalayer.entities.student", b =>
                {
                    b.Navigation("studentcourses");
                });
#pragma warning restore 612, 618
        }
    }
}
